### PR TITLE
Updated Outlook app 

### PR DESCRIPTION
**Pull request by shalin24999**
ItemAttachments will now be added when attachments are saved.

### CODE REVIEW

**Comment by frikky** [comment]
Nice!

**Comment by tyyang89** [comment]
Hi there, may i check is there any other way for us to use OWA as the "reason":"Use the Outlook Office365 app to connect to Office365. Basic auth is deprecated." , so could not link up with Outlook Office 365? Please guide me along thank you.

**Comment by frikky** [comment]
> Hi there, may i check is there any other way for us to use OWA as the "reason":"Use the Outlook Office365 app to connect to Office365. Basic auth is deprecated." , so could not link up with Outlook Office 365? Please guide me along thank you.

Hey! Please use this app instead: https://shuffler.io/apps/outlook_office365

**Comment by tyyang89** [comment]
Thank you for your reply sir. yes. i tried Auth able to link it, but i could not see any of the details of my email's body or decode any content in it to further creating my flow. (as in attachment with Google api too).

is there anyway for me to enable the body for my owa or gmail to be readable? Thanks again and have a great weekend ahead.

**Comment by frikky** [comment]
Hey, and yes there is indeed! 

- For Outlook: It looks like you're connecting to Shuffle itself on port 3443? The URL should be https://graph.microsoft.com as is the default. The /set_authentication URL should be set on the Outlook side, not in Shuffle.
- For Gmail: You're most of the way there! All you're missing is to actually get each of the emails themselves based on those ID's. Below is a workflow that shows what API (get users messages) should be used to get the actual email from the ID

https://shuffler.io/workflows/e506060f-0c58-4f95-a0b8-f671103d78e5?queryID=eacd2ee9ee4437426e35ed571d43cb61

If you need any further help, let's continue our chat on Drift :)

**Comment by tyyang89** [comment]
hi there sir. Thank you for your reply. Yes, im currently using Ubuntu 22.04 on my VM to run Shuffle. i did follow the step by step guidance provided and i think i face some redirect URI issue at Azure when authenticating. i try setting my hostname to "heronsoc" and i also try it with my IP itself but still getting the same error message.
image
image
image

While for the Gmail im still trying to construct the flow. 
By the way, Drift as in drift.com?

**Pull request merged**
