### PR TITLE
Add delete child json key

### PR DESCRIPTION
**Pull request by jeagercoder**
Before we can't delete child data like:
data = {"parent": {"child1": 1, "child2": 2}}

Now we can do it via key like a parent.child1 or parent1.parent2.child

### CODE REVIEW

**Comment by frikky** [comment]
Ahh, this is where you continued it. 

@dhaval-dave - can you test this?

**Comment by jeagercoder** [comment]
Does shuffler have a bug bounty program?

**Comment by frikky** [comment]
> Does shuffler have a bug bounty program?

Not an official one, no. I used to do security research and security things to, so if you find something juicy (which some people have), I'm sure we could work something out ;)

**Comment by frikky** [comment]
> Ahh, this is where you continued it.
> 
> @dhaval-dave - can you test this?

@dhaval-dave did you get this tested?

**Comment by dhaval055** [comment]
> > Ahh, this is where you continued it.
> > @dhaval-dave - can you test this?
> 
> @dhaval-dave did you get this tested?

Yes, it does not seem to work.

image

and I still get the same JSON back.

image

**Comment by frikky** [comment]
> > > Ahh, this is where you continued it.
> > > @dhaval-dave - can you test this?
> > 
> > 
> > @dhaval-dave did you get this tested?
> 
> Yes, it does not seem to work.
> 
> image
> 
> and I still get the same JSON back.
> 
> image

Can you fix it?

**Comment by dhaval055** [comment]
Hey!

I almost changed everything in the delete_json_keys function. Should I continue on this PR or make a new one?

**Comment by frikky** [comment]
> Hey!
> 
> I almost changed everything in the delete_json_keys function. Should I continue on this PR or make a new one?

Just continue here :) 

As long as it can do the deletes properly, then it's good

**Pull request closed without merging**
